### ISSUE TITLE
TAB does nothing for indentation

### ISSUE THREAD

**Issue by mcandre** [enriquefernandez/language-lisp#2]
In language-lisp mode, pressing TAB does nothing. It should be indenting the current line or highlighted block in Common Lisp/SLIME style.

**Comment by sjlevine** [comment]
Hello, this package isn't intended to provide proper idiomatic Lisp indentation. I'd recommend installing the `lisp-paredit` package, which does do this, and binding your TAB key to the appropriate command from that package. Works like a charm!
