### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by manishlad** [enriquefernandez/language-lisp#4]
Store package settings files in the `settings/` directory instead of `scoped-properties/`

```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:547:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:168:43)
```

**Comment by cbarrick** [comment]
Deprecated APIs are being removed in v1.0.0, which is coming out in **June**, i.e. next month. I believe simply renaming the folder would suffice.

**Comment by enriquefernandez** [comment]
I merged the pull request #5 . Hopefully that solves the issue.
Unfortunately, I haven't used atom since I first tried it last year.

**Comment by kankaristo** [comment]
The deprecation is still there, because the latest version is unpublished.

You should be able to run:

```
apm develop language-lisp  # This *should* clone the latest master
apm publish patch          # Automatically push, tag, release, etc.
```

**Comment by enriquefernandez** [comment]
I think it's published now..

**Comment by kankaristo** [comment]
Yep, thanks. :+1:
